ms.in.df <- read.csv(paste(path, "OldVersions/Oct2020/Output/InStrengthSamples_MonoCtrl.csv", sep = ""), row.names = 1)
ms.out.df <- read.csv(paste(path, "OldVersions/Oct2020/Output/OutStrengthSamples_MonoCtrl.csv", sep = ""), row.names = 1)
ms.in.new <- read.csv(paste(path, "Output/InStrengthSamples_MonoCtrl.csv", sep = ""), row.names = 1)
ms.out.new <- read.csv(paste(path, "Output/OutStrengthSamples_MonoCtrl.csv", sep = ""), row.names = 1)
ms.in.new <- subset(ms.in.new, Case == "Engel & Weltzin 2008" | Case == "Mariotte et al. 2012")
ms.out.new <- subset(ms.out.new, Case == "Engel & Weltzin 2008" | Case == "Mariotte et al. 2012")
ms.in.df <- subset(ms.in.df, Case != "Engel & Weltzin 2008" & Case != "Mariotte et al. 2012")
ms.out.df <- subset(ms.out.df, Case != "Engel & Weltzin 2008" & Case != "Mariotte et al. 2012")
ms.in.df <- rbind(ms.in.df, ms.in.new)
ms.out.df <- rbind(ms.out.df, ms.out.new)
write.csv(ms.in.df, paste(path, "Output/InStrengthSamples_Replace_MonoCtrl.csv", sep = ""))
write.csv(ms.out.df, paste(path, "Output/OutStrengthSamples_Replace_MonoCtrl.csv", sep = ""))

ms.df <- read.csv(paste(path, "OldVersions/Oct2020/Output/ModelSelectionSubset_MonoCtrl.csv", sep = ""))
ms.new <- read.csv(paste(path, "OldVersions/Oct2020/Output/ModelSelectionSubset_MonoCtrl.csv", sep = ""))
ms.new <- subset(ms.new, Case == "805_Engel_2008" | Case == "1630_Mariotte_2012")
ms.df <- subset(ms.df, Case != "805_Engel_2008" & Case != "1630_Mariotte_2012")
ms.df <- rbind(ms.df, ms.new)
write.csv(ms.df, paste(path, "Output/ModelSelectionSubset_Replace_MonoCtrl.csv", sep = ""), row.names = FALSE)